### ISSUE TITLE
D10 compatability.

### ISSUE THREAD

**Issue by jrul222** [ahebrank/eck_autolabel#1]
Need to have this module updated for D10 compatibility.  Will need to have the info file updated along with updating the eck version in the composer file to 2.0.0.  I would submit a PR but didn't look like I could even create a new branch or anything.

**Comment by ahebrank** [comment]
Thanks -- I'd done this for another project but didn't push it up. It's there now tagged as 2.0.0

**Comment by jrul222** [comment]
Awesome.  Thanks.




_______________


If you need assistance or support with Drupal please use the forms on web.uky.edu<https://web.uky.edu/>.

_______________



Regards,


Jason


[cid:6a720bdd-43ea-4268-a235-13aa47cc3956]
Jason Ullstam
University Web Operations Manager
University of Kentucky
Marketing & Brand Strategy
Web Communications
***@***.***


***@***.***?anonymous&ep=signature>          Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________

**Comment by jrul222** [comment]
Actually still needs the composer file updated...  the eck module itself has a 2.0.0 supported release for D9 & D10...

 "drupal/eck": "~1", Needs to be  "drupal/eck": "^2.0.0"

**Comment by ahebrank** [comment]
OK, in 2.0.1
